project:
  type: website
  output-dir: docs

website:
  title: "Jordan Miller's Website Warmup"
  site-path: "/warmup-jordan-miller/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: articles/index.qmd
        text: Articles 

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Article 1: Chessboard Problem"
          href:  articles/article_01.qmd
        - text: "Article 2: Sum of a Range Problem"
          href:  articles/article_02.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



